
@host = http://localhost:3030/api/v1

# @name register 
POST {{host}}/user/register HTTP/1.1
Content-Type: application/json

{
	"name": "TestUser",
	"bot": false,
	"password": "TestPass"
}

###
@userid = {{register.response.body._id}}

# @name login
POST {{host}}/user/{{userid}}/login HTTP/1.1
Content-Type: application/json

{
	"password": "TestPass"
}

###
@token = {{login.response.body.token}}

# @name createSpace
POST {{host}}/space/create HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
	"name": "TestSpace"
}

###
@space = {{createSpace.response.body._id}}

# @name getSpace
GET {{host}}/space/{{space}} HTTP/1.1
Authorization: {{token}}